diplom2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from find import views
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('admin/', admin.site.urls, name='admin'),
    path('', views.index),
	path('about/', views.about),
	path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
	path('regis/', views.regis, name='regis'),
	path('post_missing/', views.post_missing),
    path('post_victim/', views.post_victim),
    path('posts/', views.PostList.as_view()),
    path('thanks/', views.thanks, name='thanks'),
    path('image/', views.image),
    #path('post/<int:pk>/', views.PostDetail.as_view(), name='post'),
    path('post/<int:pk>/', views.post_detail, name='post'),
    path('mypost/', views.Mypost.as_view(), name='mypost'),
    path('delete/', views.delete_everything),
    path('train/', views.train),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

find/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    # path('missing', views.post_missing, name='post_missing'),
    # # path('victim', views.victim),
    # path('thanks/', views.thanks, name='thanks'),
    #path('posts/', views.PostList.as_view(template_name='posts.html'), name='post'),
    # path('image/', views.image),
    # path('test/', views.test),
    # path('<int:pk>/', views.mypost, name='post')
]

find/models.py
from django.db import models
import os
import datetime
from django.contrib.auth.models import User
from uuid import uuid4
from django.conf import settings
from django.utils.deconstruct import deconstructible



@deconstructible
class PathAndRename(object):
	def __init__(self, sub_path):
		self.path = sub_path

	def __call__(self, instance, filename):
		ext = filename.split('.')[-1]
		# set filename as random string
		filename = '{}.{}'.format(instance.id, ext)
		# return the whole path to the file
		return os.path.join(self.path, filename)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_ROOT = os.path.join(BASE_DIR, 'images')
path_and_rename_missing = PathAndRename(os.path.join(BASE_DIR, 'images/missing'))
path_and_rename_victim = PathAndRename(os.path.join(BASE_DIR, 'images/victim'))


class Post_type(models.Model):
    type_name = models.CharField(max_length=50)

    def __str__(self):
        return self.type_name

    class Admin: pass


class Relative(models.Model):
    fullname = models.CharField(max_length=50)
    address = models.CharField(max_length=100, null=True)
    telephone = models.CharField(max_length=12)
    email = models.EmailField(null=True)

    def __str__(self):
        return self.fullname

    class Admin: pass


    
class Post(models.Model):
    text = models.TextField()
    time = models.DateTimeField(default = datetime.datetime.now())
    found = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    post_type = models.ForeignKey(Post_type, on_delete=models.CASCADE, default=None)
    relative = models.ForeignKey(Relative, on_delete=models.CASCADE, default=None)
    # missing_person_id = models.ForeignKey(Missing_person, on_delete=models.CASCADE, default=None)
    # victim_id = models.ForeignKey(Victim, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.text

    class Admin: pass



class Missing_person(models.Model):
    name = models.CharField(max_length=50)
    nickname = models.CharField(max_length=20, null=True)
    birthday = models.DateField()
    missing_place = models.CharField(max_length=100)
    missing_time = models.DateField()
    status = models.CharField(max_length=20)
    image = models.ImageField(upload_to=path_and_rename_missing, default = 'images/non.png')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None, related_name='missing')


    def __str__(self):
        return self.name

    class Admin: pass



class Victim(models.Model):
    date = models.DateField()
    place = models.CharField(max_length=100)
    image = models.ImageField(upload_to=path_and_rename_victim, default = 'images/non.png')
    additional_information = models.CharField(max_length=50, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None, related_name='victim')

    def __str__(self):
        return str(self.id)

    class Admin: pass



class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)


class Match(models.Model):
   missing_person = models.ForeignKey(Missing_person, on_delete=models.CASCADE, related_name="missing_person")
   victim = models.ForeignKey(Victim, on_delete=models.CASCADE, related_name="victim_person")
   exactly = models.BooleanField(default=False)

   class Admin: pass



    

find/forms.py
from . import models
from django import forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist


class DateInput(forms.DateInput):
    input_type = 'date'


class PostForm(forms.ModelForm):
	class Meta:
		model = models.Post
		fields = ['text']
		

	# def save(self):


class RelativeForm(forms.ModelForm):
	class Meta:
		model = models.Relative
		fields = '__all__'

	# def save(self):
	# 	Relative.objects.create(fullname=self.cleaned_data['fullname'], telephone=self.cleaned_data['telephone'], adress=self.cleaned_data['adress'], email=self.cleaned_data['email'])

class Missing_personForm(forms.ModelForm):
	class Meta:
		model = models.Missing_person
		fields = ['name', 'nickname', 'birthday', 'missing_place', 'missing_time', 'status', 'image']
		widgets = {
            'birthday': DateInput(),
            'missing_time' : DateInput(),
        }


	# def save(self):
	# 	Missing_person.objects.create(name=self.cleaned_data['name'], nickname=self.cleaned_data['nickname'], birthday=self.cleaned_data['birthday'], missing_place=self.cleaned_data['missing_place'], missing_time=self.cleaned_data['missing_time'], status=self.cleaned_data['status'])


class VictimForm(forms.ModelForm):

	# def save(self,commit=True):
	# 	victim = super().save()
	# 	image = self.cleaned_data['image']
	# 	victim.image = image
	# 	victim.save()

	class Meta:
		model = models.Victim
		fields = ['date', 'place', 'image', 'additional_information']

		widgets = {
            'date': DateInput(),
        }


class RegistrationForm(forms.Form):
	fullname = forms.CharField(label="ФИО", max_length=50, initial='')
	username = forms.CharField(label="Логин", max_length=30)
	email = forms.EmailField(label="Эл. почта", initial='xyz@mail.com')
	password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput())
	password2 = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput())
	
	def __init__(self, *args, **kwargs):
		super(RegistrationForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'txt'
	
	def clean_password2(self):
		if 'password1' in self.cleaned_data:
			password1 = self.cleaned_data['password1']
			password2 = self.cleaned_data['password2']
			if password1==password2:
				return password2
		raise forms.ValidationError("Пароли не совпадают")

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			User.objects.get(username=username)
		except ObjectDoesNotExist:
			return username
		raise forms.ValidationError("Логин уже существовал. Выбрайте другой пожалуйста!")

	def save(self):
		User.objects.create_user(username=self.cleaned_data['username'], email=self.cleaned_data['email'], first_name=self.cleaned_data['fullname'],password=self.cleaned_data['password1'])



class CommentForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user', None)
		self.post = kwargs.pop('post', None)

		super().__init__(*args, kwargs)

	def save(self, commit=True):
		comment = super().save(commit=False)
		comment.user = self.user
		comment.post = self.post
		comment.save()

	class Meta:
		model = models.Comment
		fields = ['content']

templates/about.html
{% extends "template.html" %}

{% block css %}{% endblock %}

{% block content %}
	<div class="content">
		<h1 class="title">Насчет нас</h1>
		<p>Надежда - это продукт дипломной работы. Мы собрались вместе, чтобы помощи в воссоединении пропавших людей со своими семьями. Ребенок может быть потерян, и он не может найти дорогу домой. Взрослый с проблемами психического здоровья может быть потерян, и он или она не сможет найти дорогу к своим семьям. Они томятся и страдают, а их семьи скорбят и лихорадочно ищут. Наша миссия - помочь таким потерянным детям или взрослым воссоединиться со своими семьями.<p>

		<p>Проект также содержит много недостатков, которые требуют дальнейших исследований для улучшения. Мы очень благодарены, если в будущем сможем получить помощь от частных лиц и организаций, чтобы улучшить и ввести этот продукт в действие.<p>
	</div>

{% endblock %}

{% block js %}{% endblock %}

templates/guide.html
{% extends "base.html" %}

	{% block css %}
		<link rel="stylesheet" href="css/guide1.css">
	{% endblock %}
	{% block content %}
        <div class="container content">
        	<h1>Попытаете найти потерянного родственника?</h1>
        	<div class="row">
        		<div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
        			<div class="container-fluid">
        				<div class="row">
        					<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
        						<p>Люди теряют связь по многим причинам - аргумент, который вышел из-под контроля, переезд за границу, развод. Все эти вещи могут разорвать семью на части, а затем, когда вы захотите собрать ее воедино, вы не знаете, с чего начать. Независимо от того, почему вы потеряли связь, Genes Reunited может помочь вам найти того, кого вы ищете. Воссоединение с давно потерянными отношениями может быть эмоциональным переживанием, поэтому мы рекомендуем поговорить об этом с другом или партнером, который может поддержать вас в пути. Удачи!</p>
        					</div>
        					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        						<img src="images/family.jpg" class="img-responsive" alt="">
        					</div>
        				</div>
        				<div class="row"><h2>Что делаете</h2></div>
        				<div class="row">
        					<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        						<h4>Шаг 1: </h4>
        					</div>
        					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
        						<p>Download our eBook - It's a free guide that’s packed with detailed advice on finding lost relatives as well as links to some professional services that may be able to help you.</p>
        					</div>
        				</div>        				
        				<div class="row">
        					<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        						<h4>Шаг 1: </h4>
        					</div>
        					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
        						<p>Download our eBook - It's a free guide that’s packed with detailed advice on finding lost relatives as well as links to some professional services that may be able to help you.</p>
        					</div>
        				</div>        				
        				<div class="row">
        					<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        						<h4>Шаг 1: </h4>
        					</div>
        					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
        						<p>Download our eBook - It's a free guide that’s packed with detailed advice on finding lost relatives as well as links to some professional services that may be able to help you.</p>
        					</div>
        				</div>        				
        				<div class="row">
        					<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        						<h4>Шаг 1: </h4>
        					</div>
        					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
        						<p>Download our eBook - It's a free guide that’s packed with detailed advice on finding lost relatives as well as links to some professional services that may be able to help you.</p>
        					</div>
        				</div>
        			</div>
        		</div>
        	</div>
        </div>  <!-- end content -->

    {% endblock %}

templates/image.html
{% extends "template.html" %}

{% block css %}{% endblock %}

{% block content %}
<p>{{}}</p>
	
<img src="{{image.image.url}}">

{% endblock %}

{% block js %}{% endblock %}

templates/index.html
{% extends "template.html" %}

{% block css %}{% endblock %}

{% block content %}
	<div class="content">
	<h1 class="title">Пытаетесь найти потерянного родственника?</h1>
	<p>Люди теряют связь по многим причинам - аргумент, который вышел из-под контроля, переезд за границу, развод. Все эти вещи могут разорвать семью на части, а затем, когда вы захотите собрать ее воедино, вы не знаете, с чего начать. Независимо от того, почему вы потеряли связь, Genes Reunited может помочь вам найти того, кого вы ищете. Воссоединение с давно потерянными отношениями может быть эмоциональным переживанием, поэтому мы рекомендуем поговорить об этом с другом или партнером, который может поддержать вас в пути. Удачи!</p>
	<p>Что делать сейчас:</p>
	<p>Шаг 1: Регистрируете на сайте <a href="/regis">здесь</a> чтобы мы знаем кого сообщать если есть новую информацию.</p>
	<p>Шаг 2: Разместите информации опропавшем человеке <a href="/post">здесь.</a> Обратите внимание, что тем больше информации чем выше возможность успеха.</p>
	<p>Шаг 3: Регулярно проверять <a href="/messages">мои сообщения.</a></p>
	</div>
{% endblock %}

{% block js %}{% endblock %}

templates/login.html
{% extends "template.html" %}

{% block css %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/login3.css' %}">
{% endblock %}

{% block content %}
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-push-2">
	<div class="login">
	
	<form action="." method="POST">
		{% csrf_token %}
		{% for key,value in form.errors.items %}
			{{value}}
		{% endfor %}
<!-- 		<p><label for="">Логин :</label>{{form.username}}</p><br>	
<p><label for="">Парол :</label>{{form.password}}</p>
<input type="hidden" name='next' value='/'>
<input type="submit" value='Submit'class="btn btn-primary">  -->
 		    <h1>Войти</h1>
			<p>{{form.username}}</p>
			<p>{{form.password}}</p> 
			<input type="hidden" name='next' value='/'>
			<p class="submit"><input type="submit" name="commit" value="Войти"></p>
		      <!-- <form method="post" action="index.html"> -->
<!-- 		        <p><input type="text" name="login" value="" placeholder="Логин"></p>
<p><input type="password" name="password" value="" placeholder="Парол"></p> -->
<!-- 		        <p class="remember_me">
  <label>
    <input type="checkbox" name="remember_me" id="remember_me">
    Remember me on this computer
  </label>
</p> -->
		       <!--  <p class="submit"><input type="submit" name="commit" value="Войти"></p> -->
		      <!-- </form> -->
	</form>
	</div> <!-- end login_form -->
</div> <!-- end col -->
{% endblock %}

{% block js %}
<script src="{% static 'js/login1.js' %}"></script>
{% endblock %}

templates/post_detail.html
{% extends "template.html" %}

{% block css %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/post_detail2.css' %}">
{% endblock %}

{% block content %}
<div class="content">
	<h3 id="title">{{post.post_type}}({{post.id}})</h3>
		<p class="time">{{post.time}}</p>
		<!-- <p>{{post.found}}</p> -->
		<p id="text">{{post.text}}</p>

		{% for m in post.missing.all %}
			<div class="image"><img src="{{m.image.url}}" alt=""></div>
			<h5>Соотвествующие новости:</h5>
			{% for mp in m.missing_person.all %}	
				<p><strong><a href="/post/{{mp.victim.post.id}}">{{mp.victim.post.post_type}} ({{mp.victim.post.id}})</a></strong></p>
			{% endfor %}
		{% endfor %}
		{% for v in post.victim.all %}
			<div class="image"><img src="{{v.image.url}}" alt=""></div>
			<h5>Соотвествующие новости:</h5>
			{% for vp in v.victim_person.all %}	
				<p><strong><a href="/post/{{vp.missing_person.post.id}}">{{vp.missing_person.post.post_type}} ({{vp.missing_person.post.id}})</a></strong></p>
			{% endfor %}
		{% endfor %}
	<hr id="in_content" width="100%" align="center">
	<div class="comments">
		<h4><strong>Комментарий</strong></h4>
		{% for comment in post.comments.all %}
			<p class="comment"><strong class="author">{{comment.user}}</strong>  -  {{comment.content}}</p>
			<p class="time">{{comment.time}}</p>
			<hr id="in_comment" width="80%" align="center">
		{% endfor %}

		{% if user.username %}
			<form action="{% url 'post' post.id %}" method='POST'>
				{% csrf_token %}
	<!-- 			<p><label for="">Комментарий</label></p> -->
				{{form.content}}
				<br>
				<input type="submit" value="Комментировать">
			</form>
		{% else %}
			<p>Только полноправные пользователи могут оставлять комментарии. Войдите, пожалуйста!</p>
		{% endif%}
		</div>

</div>
{% endblock %}

{% block js %}{% endblock %}

templates/post_missing.html
{% extends "template.html" %}

{% block css %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/regis1.css' %}">
	<link rel="stylesheet" href="{% static 'css/regis2.css' %}">
	<link rel="stylesheet" href="{% static 'css/post_missing3.css' %}"> 
{% endblock %}

{% block content %} 
<div class="content">
	<div id="responsive-form" class="clearfix">
	<form action="." method="POST" enctype="multipart/form-data">
		{% csrf_token %}

<!-- 		<div class="form-row">
<div class="column-half">First Name [text* first-name]</div>
<div class="column-half">Last Name [text* last-name]</div>
</div> -->

		<div class="missing">
			<h4>Информации о пропавшем человеке:</h4>
			<p class="input"><label for="id_name">ФИО</label>{{form2.name}}</p>
			<p class="input"><label for="id_nickname">Сокрашенное имя</label>{{form2.nickname}}</p>
			<p class="input"><label for="id_birthday">День рождения</label>{{form2.birthday}}</p>
			<p class="input"><label for="id_missing_place">Где потерял</label>{{form2.missing_place}}</p>
			<p class="input"><label for="id_missing_time">Когда потерял</label>{{form2.missing_time}}</p>
			<p class="input"><label for="id_status">Состояние</label>{{form2.status}}</p>
			<div><label for="id_image">Изображение</label>{{form2.image}}</div>
		</div>

		<br>
		<div class="relative">
			<p>Кем сообщит если есть новую информацию?</p>
			<p class="input"><label for="id_fullname">ФИО</label>{{form3.fullname}}</p>
			<p class="input"><label for="id_address">Адрес</label>{{form3.address}}</p>
			<p class="input"><label for="id_telephone">Телефон</label>{{form3.telephone}}</p>
			<p class="input"><label for="id_email">Эл. почта</label>{{form3.email}}</p>
		</div>

		<div class="post">
			<p class="txtarea_input"><label for="id_text">Содержание</label>{{form1.text}}</p>
		</div>
		<input type="hidden" name='next' value='/login'>
		<input class="btn btn-primary" type="submit" value="Продолжить">
	</form>
	</div><!--end responsive-form-->

</div> <!-- end div content -->
{% endblock %}

{% block js %}
<script src="{% static 'js/post_missing1.js' %}"></script>
{% endblock %}

templates/post_victim.html
{% extends "template.html" %}

{% block css %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/regis1.css' %}">
	<link rel="stylesheet" href="{% static 'css/regis2.css' %}">
	<link rel="stylesheet" href="{% static 'css/post_missing3.css' %}"> 
	<link rel="stylesheet" href="{% static 'css/post_victim1.css' %}"> 

{% endblock %}

{% block content %}
<div class="content">
	{% if form.errors %}
        <p class="error">Возникла проблема. Проверьте пожалуйста!</p>
    {% endif %} 
	<form action="." method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="post">
			<p class="txtarea_input"><label for="id_text">Содержание </label>{{form1.text}}</p>
		</div>
		<br>
		<div class="relative">
			<p>Кем сообщит если есть новую информацию?</p>
			<p class="input"><label for="id_fullname">ФИО</label>{{form3.fullname}}</p>
			<p class="input"><label for="id_address">Адрес</label>{{form3.address}}</p>
			<p class="input"><label for="id_telephone">Телефон</label>{{form3.telephone}}</p>
			<p class="input"><label for="id_email">Эл. почта</label>{{form3.email}}</p>
		</div>
		<br>
		<div class="victim">
			<p>Информации о найденном человеке:</p>
			<p class="input"><label for="id_place">Где увиделся</label>{{form2.place}}</p>
			<p class="input"><label for="id_date">Когда увиделся</label>{{form2.date}}</p>
			<p ><label for="">Изображение</label>{{form2.image}}</p>
			<p class="input"><label for="id_additional_information">Другие информации</label>{{form2.additional_information}}</p>
		</div>
		<button type="submit" class="btn btn-primary" class="submit">Продолжать</button>
	</form>
</div>
{% endblock %}

{% block js %}
	<script src="{% static 'js/post_missing1.js' %}"></script>
{% endblock %}

templates/posts.html
{% extends "template.html" %}

{% block css %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/posts1.css' %}">
{% endblock %}

{% block content %}

	{% for post in object_list %}
		<div class="post content">
			<h3 ><a class="title" href="/post/{{post.id}}">{{post.post_type}} ({{post.id}})</a></h3>
			<p class="time">{{post.time}}</p>
			<p>{{post.text}}</p>
			<!-- <p>{{post.relative}}</p> -->
			{% for m in post.missing.all %}
				<div class="image"><img src="{{m.image.url}}" alt=""></div>
				<h5>Соотвествующие новости:</h5>
				{% for mp in m.missing_person.all %}
					<p><a href="/post/{{mp.victim.post.id}}">{{mp.victim.post.id}}</a></p>
				{% endfor %}

			{% endfor %}
			{% for v in post.victim.all %}
				<div class="image"><img src="{{v.image.url}}" alt=""></div>
				<h5>Соотвествующие новости:</h5>
				{% for vp in v.victim_person.all %}	
					<p><a href="/post/{{vp.missing_person.post.id}}">{{vp.missing_person.post.id}}</a></p>
				{% endfor %}
			{% endfor %}	
		<br>
		<br>
		</div>

	{% endfor %}


<br>
{% if page_obj.has_next %}
	<a href="{{request.path}}?page={{page_obj.next_page_number}}">Next</a>
{% endif %}

{% endblock %}

{% block js %}{% endblock %}

templates/regis.html
{% extends "template.html" %}
<!-- {% load static %} -->

	{% block css %}
		<link rel="stylesheet" href="{% static 'css/regis1.css' %}">
		<link rel="stylesheet" href="{% static 'css/regis2.css' %}">
	{% endblock %}
	{% block content %}
	<div class="content">
	      {% if form.errors %}
        <p class="error">Lo sentimos, la combinacion de usuario y contrasena no es correcta!</p>
      {% endif %}  
					<div class="background">
					
<!-- 						<form action="." method="POST" role="form">
	<input type='hidden' name='csrfmiddlewaretoken' value='randomchars' />
	{% csrf_token %}
	{{ form.as_p }}

	<div class="but">
	<button type="submit" class="btn btn-primary" class="submit">Продолжать</button>
	</div>
</form> -->

						<form id="contactform" name="contact" method="POST" action="." role="form">
							<input type='hidden' name='csrfmiddlewaretoken' value='randomchars' />
							{% csrf_token %}
						  <p class="note"><span class="req">*</span> Поля звездочки обязательны для заполнения</p>
						  <div class="row">
						    <label for="id_fullname">ФИО <span class="req">*</span></label>
						    {{form.fullname}}
						  </div>			

						  <div class="row">
						    <label for="id_username">Логин <span class="req">*</span></label>
						    {{form.username}}
						  </div>
						 
						  <div class="row">
						    <label for="id_email">Эл. почта <span class="req">*</span></label>
						    {{form.email}}
						  </div>
						 
						  <div class="row">
						    <label for="id_password1">Пароль <span class="req">*</span></label>
						    {{form.password1}}
						  </div>						  

						  <div class="row">
						    <label for="id_password2">Подтвердите пароль <span class="req">*</span></label>
						    {{form.password2}}
						  </div>
						 
<!-- 						  <div class="row">
  <label for="message">Подтвердите пароль <span class="req">*</span></label>
  <textarea name="message" id="message" class="txtarea" tabindex="4" required></textarea>
</div> -->
						 
						  <div class="center">
						    <input class="btn btn-success" type="submit" id="submitbtn" name="submitbtn" tabindex="5" value="Зарегистрироваться">
						  </div>
						</form>
					</div>
	</div>
	{% endblock %}

templates/result.html
{% extends "template.html" %}

{% block css %}{% endblock %}

{% block content %}
	
	<h1>{{id}}</h1>

{% endblock %}

{% block js %}{% endblock %}

templates/thanks.html
{% extends "template.html" %}

{% block css %}{% endblock %}

{% block content %}
	
<h1>Thanks</h1>

{% endblock %}

{% block js %}{% endblock %}